M48
; DRILL file {KiCad (6.0.2)} date Tue Jun  7 21:46:54 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-07T21:46:54+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.500
%
G90
G05
T1
X123.305Y-55.23
X128.155Y-55.23
T2
X123.005Y-52.2
X128.455Y-52.2
T3
X142.12Y-60.2
X142.12Y-83.06
X164.98Y-60.2
X164.98Y-83.06
T4
X153.964Y-98.014
X153.964Y-128.014
T0
M30
